version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins:2.263.1-lts-centos7
    container_name: brq-jenkins
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - tools
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  sonarqube:
    image: sonarqube:8.6.0-community
    container_name: brq-sonarqube
    depends_on:
      - db-sonar
    ports:
      - "8081:9000"
    networks:
      - tools
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db-sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  portainer:
     image: portainer/portainer:1.24.1-alpine
     container_name: brq-portainer
     ports:
       - "9000:9000"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data
     networks:
       - tools
     command: -H unix:///var/run/docker.sock

  nexus:
    image: sonatype/nexus3:3.29.2
    container_name: brq-nexus
    ports:
      - "8082:8081"
      - "9001:9000"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - tools

  db-sonar:
    image: postgres:12-alpine
    container_name: brq-db-postgres-sonarqube
    networks:
      - tools
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql_sonar_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - "node.role==manager"

networks:
  tools:
    name: brq-tools
    driver: overlay
    attachable: true

volumes:
  jenkins_data:
    name: jenkins_data
  sonarqube_conf:
    name: sonarqube_conf
  sonarqube_data:
    name: sonarqube_data
  sonarqube_extensions:
    name: sonarqube_extensions
  sonarqube_logs:
    name: sonarqube_logs
  sonarqube_temp:
    name: sonarqube_temp
  portainer_data:
    name: portainer_data
  nexus_data:
    name: nexus_data
  postgresql_sonar_data:
    name: postgresql_sonar_data
