version: "3.7"
services:
  ecash-qa:
    image: 10.2.0.138:9001/volvo-ms-ecash-qa:latest
    environment: 
      ASPNETCORE_ENVIRONMENT: qa
    ports:
      - "5002:80"
  ecash-dev:
    image: 10.2.0.138:9001/volvo-ms-ecash-dev:latest
    environment: 
      ASPNETCORE_ENVIRONMENT: development
    ports:
      - "5004:80"
